name: exemplo_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  gradient_widgets: ^0.6.0
  cached_network_image: ^3.2.0
  geocoding: ^3.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^0.13.6
  geolocator: ^13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icones/homem1.png
    - assets/icones/homem2.png
    - assets/icones/homem3.png
    - assets/icones/homem4.png
    - assets/icones/homem5.png
    - assets/icones/homem6.png
    - assets/icones/mulher1.png
    - assets/icones/mulher2.png
    - assets/icones/mulher3.png
    - assets/icones/mulher4.png
    - assets/icones/mulher5.png
    - assets/icones/mulher6.png